import { Offer, LiveClaim, UserReview } from './types';

export const USA_OFFERS: Offer[] = [
  {
    id: 'paypal-750',
    title: '$750 PayPal Gift Card',
    category: 'Gift Card',
    description: 'Claim your $750 PayPal balance gift card. Complete the quick consumer survey and brand questionnaire.',
    requirement: 'Submit email & short survey',
    difficulty: 'Medium',
    icon: 'Wallet',
    estTime: '3-4 mins',
    rating: 4.9,
    featured: true,
    rewardValue: '$750.00',
    payoutPoints: 500,
  },
  {
    id: 'iphone-16',
    title: 'iPhone 16 Pro Sweepstakes',
    category: 'Email Submit',
    description: 'Enter your email address for a chance to win a brand new titanium iPhone 16 Pro. Verified instant-draw.',
    requirement: 'Submit and verify email',
    difficulty: 'Easy',
    icon: 'Mail',
    estTime: '1-2 mins',
    rating: 4.8,
    featured: true,
    rewardValue: '$999.00',
    payoutPoints: 200,
  },
  {
    id: 'premium-wallpapers',
    title: 'Retro Arcade Mobile Access',
    category: 'Pin Submit',
    description: 'Unlock direct premium mobile access to 100+ retro arcade games and ultra HD live wallpapers.',
    requirement: 'Mobile number PIN confirmation',
    difficulty: 'Easy',
    icon: 'Smartphone',
    estTime: '2 mins',
    rating: 4.6,
    featured: false,
    rewardValue: 'Unlimited Access',
    payoutPoints: 350,
  },
  {
    id: 'secure-vpn',
    title: 'SmartSecure VPN & Guard',
    category: 'App Install',
    description: 'Install and start the top-rated SmartSecure VPN. Protect your data with military-grade encryption.',
    requirement: 'Install and run for 30s',
    difficulty: 'Easy',
    icon: 'Download',
    estTime: '2 mins',
    rating: 4.7,
    featured: false,
    rewardValue: 'Free Premium Week',
    payoutPoints: 150,
  },
  {
    id: 'cash-app-500',
    title: '$500 Cash App Transfer',
    category: 'Gift Card',
    description: 'Get an instant $500 Cash App balance credit. Limited daily slots available for US consumers.',
    requirement: 'Complete survey & verify number',
    difficulty: 'Medium',
    icon: 'Gift',
    estTime: '4 mins',
    rating: 4.9,
    featured: false,
    rewardValue: '$500.00',
    payoutPoints: 450,
  },
  {
    id: 'walmart-1000',
    title: '$1,000 Walmart Shopping Spree',
    category: 'Email Submit',
    description: 'Select your preferred departments and submit your email to receive a $1,000 digital Walmart shopping card.',
    requirement: 'Email sign-up & select preference',
    difficulty: 'Easy',
    icon: 'Mail',
    estTime: '2 mins',
    rating: 4.7,
    featured: true,
    rewardValue: '$1,000.00',
    payoutPoints: 400,
  }
];

export const MOCK_LIVE_CLAIMS: LiveClaim[] = [
  {
    id: 'claim-1',
    name: 'Sarah M.',
    location: 'Houston, TX',
    offerTitle: '$750 PayPal Gift Card',
    timeAgo: 'Just now',
    avatarSeed: 'sarah',
  },
  {
    id: 'claim-2',
    name: 'David K.',
    location: 'Denver, CO',
    offerTitle: 'iPhone 16 Pro Sweepstakes',
    timeAgo: '2 mins ago',
    avatarSeed: 'david',
  },
  {
    id: 'claim-3',
    name: 'Jessica T.',
    location: 'Miami, FL',
    offerTitle: '$1,000 Walmart Shopping Spree',
    timeAgo: '5 mins ago',
    avatarSeed: 'jessica',
  },
  {
    id: 'claim-4',
    name: 'Michael B.',
    location: 'Phoenix, AZ',
    offerTitle: 'Retro Arcade Mobile Access',
    timeAgo: '8 mins ago',
    avatarSeed: 'michael',
  },
  {
    id: 'claim-5',
    name: 'Ashley R.',
    location: 'Atlanta, GA',
    offerTitle: 'SmartSecure VPN & Guard',
    timeAgo: '12 mins ago',
    avatarSeed: 'ashley',
  },
];

export const MOCK_REVIEWS: UserReview[] = [
  {
    id: 'rev-1',
    name: 'James Henderson',
    location: 'Boston, MA',
    rating: 5,
    comment: 'Honestly, I was skeptical at first, but I completed the PayPal survey, entered my email, and got the code in my inbox about an hour later. Real and fast!',
    date: 'July 10, 2026',
    avatarSeed: 'james',
    verified: true,
  },
  {
    id: 'rev-2',
    name: 'Emily Davis',
    location: 'San Jose, CA',
    rating: 5,
    comment: 'The VPN install took 1 minute. It is actually a really good VPN too, keep it installed for protection now. App installation offers are so easy to do!',
    date: 'July 9, 2026',
    avatarSeed: 'emily',
    verified: true,
  },
  {
    id: 'rev-3',
    name: 'Brandon Torres',
    location: 'Dallas, TX',
    rating: 4,
    comment: 'Did the pin submit for retro games. My kids love playing it on the iPad. Highly recommend this portal if you have 5 minutes to spare.',
    date: 'July 8, 2026',
    avatarSeed: 'brandon',
    verified: true,
  },
  {
    id: 'rev-4',
    name: 'Megan Smith',
    location: 'Columbus, OH',
    rating: 5,
    comment: 'I am so happy! Entered the Walmart shopping card sweepstakes and actually got the $1000 credit today. Already bought a new TV!',
    date: 'July 5, 2026',
    avatarSeed: 'megan',
    verified: true,
  },
];

export const QUIZ_QUESTIONS = [
  {
    id: 1,
    question: 'Are you currently located in the United States?',
    options: ['Yes, absolutely', 'No, visiting/other'],
  },
  {
    id: 2,
    question: 'Which device are you currently using to complete these offers?',
    options: ['Apple iOS (iPhone/iPad)', 'Android Mobile / Tablet', 'Windows or Mac Computer'],
  },
  {
    id: 3,
    question: 'How do you plan to use your reward card or premium credits?',
    options: ['Personal Shopping', 'Gifts for Friends/Family', 'Save for emergencies'],
  },
];
